# Site settings
title: Mastiff Gaming
description: Indie game studio creating chaotic and stylized experiences.
url: "https://mastiff-systems343.github.io/"
baseurl: "/gaming"
timezone: America/Chicago
future: true

# SEO
logo: /images/logo.png
tagline:
author:
  name: Mastiff Gaming
  email:
  bluesky: mastiffgaming.bsky.social
  phone: ""
social:
  name: Mastiff Gaming
  links:
    - https://github.com/mastiff-systems

# Build settings
markdown: kramdown
permalink: /:title/

# Collections
collections:
  games:
    _hide_content: false
    output: true
  products:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-leaflet
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate

# Pagination
paginate: 3
paginate_path: "/blog/page/:num/"

# Archives
jekyll-archives:
  enabled: ['all']
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'
  category_archive:
    type: liquid

# Includes / Excludes
include:
  - .htaccess
  - _pages


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - LICENCE
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Contact
formcarry: https://formcarry.com/

# Social icons (if theme supports them)
social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
